global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8000"]

  - job_name: "mysql"
    static_configs:
      - targets: ["mysql_exporter:9104"]
      
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
